### ISSUE TITLE
[1.10.2]  java.lang.IllegalArgumentException: Name and ID cannot both be blank

### ISSUE THREAD

**Issue by L4BORG** [TacoSpigot/TacoSpigot#40] opened 2016-06-28 01:27 UTC
```
[03:26:18 WARN]: java.lang.IllegalArgumentException: Name and ID cannot both be blank
[03:26:18 WARN]:        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:25)
[03:26:18 WARN]:        at net.minecraft.server.v1_10_R1.UserCache.a(UserCache.java:90)
[03:26:18 WARN]:        at net.minecraft.server.v1_10_R1.UserCache.getProfile(UserCache.java:158)
[03:26:18 WARN]:        at net.minecraft.server.v1_10_R1.Village.b(Village.java:444)
[03:26:18 WARN]:        at net.minecraft.server.v1_10_R1.PersistentVillage.b(PersistentVillage.java:256)
[03:26:18 WARN]:        at net.minecraft.server.v1_10_R1.PersistentCollection.a(PersistentCollection.java:99)
[03:26:18 WARN]:        at net.minecraft.server.v1_10_R1.PersistentCollection.a(PersistentCollection.java:84)
[03:26:18 WARN]:        at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1083)
[03:26:18 WARN]:        at net.minecraft.server.v1_10_R1.WorldServer.save(WorldServer.java:1024)
[03:26:18 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.save(CraftWorld.java:823)
[03:26:18 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:755)
[03:26:18 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629)
[03:26:18 WARN]:        at java.lang.Thread.run(Thread.java:745)
```
```
>ver
[03:27:27 INFO]: This server is running Paper version git-TacoSpigot-"0972f16" (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
[03:27:27 INFO]: You are running the latest version
```

**Comment by Techcable** [comment] 2016-06-28 02:53
Duplicate of PaperMC/Paper#347

**Closed by Techcable** 2016-06-28 02:53 UTC
