### ISSUE TITLE
[1.10.2] java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot set property BlockStateInteger

### ISSUE THREAD

**Issue by L4BORG** [TacoSpigot/TacoSpigot#39] opened 2016-06-28 01:25 UTC
```
[03:20:43] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot set property BlockStateInteger{name=rotation, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockStateList{block=minecraft:standing_banner, properties=[rotation]}
    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_92]
    at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_92]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:46) [patched.jar:git-TacoSpigot-"0972f16"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:793) [patched.jar:git-TacoSpigot-"0972f16"]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:403) [patched.jar:git-TacoSpigot-"0972f16"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:730) [patched.jar:git-TacoSpigot-"0972f16"]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:629) [patched.jar:git-TacoSpigot-"0972f16"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.IllegalArgumentException: Cannot set property BlockStateInteger{name=rotation, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockStateList{block=minecraft:standing_banner, properties=[rotation]}
    at net.minecraft.server.v1_10_R1.BlockStateList$BlockData.set(BlockStateList.java:193) ~[patched.jar:git-TacoSpigot-"0972f16"]
    at net.minecraft.server.v1_10_R1.ItemBanner.a(SourceFile:60) ~[patched.jar:git-TacoSpigot-"0972f16"]
    at net.minecraft.server.v1_10_R1.ItemStack.placeItem(ItemStack.java:121) ~[patched.jar:git-TacoSpigot-"0972f16"]
    at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:532) ~[patched.jar:git-TacoSpigot-"0972f16"]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:893) ~[patched.jar:git-TacoSpigot-"0972f16"]
    at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) ~[patched.jar:git-TacoSpigot-"0972f16"]
    at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) ~[patched.jar:git-TacoSpigot-"0972f16"]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) ~[patched.jar:git-TacoSpigot-"0972f16"]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_92]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) ~[patched.jar:git-TacoSpigot-"0972f16"]
    ... 5 more
```

```
>ver
[03:24:39 INFO]: This server is running Paper version git-TacoSpigot-"0972f16" (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
[03:24:39 INFO]: Checking version, please wait...
[03:24:39 INFO]: You are running the latest version
```

**Comment by Techcable** [comment] 2017-06-20 19:32
Duplicate of #47, which was fixed in 8855fae.

**Closed by Techcable** 2017-06-20 19:32 UTC
