### ISSUE TITLE
[1.10.2] b#79 - Bugged pistons

### ISSUE THREAD

**Issue by L4BORG** [TacoSpigot/TacoSpigot#43] opened 2016-07-04 13:09 UTC
Pistons will turn into drops when activated.

How? Place piston on the floor, place lever next to piston, trigger lever - piston will extend and block will disappear (there will be piston dropped...) and there will be extended piston head.

**Comment by sgdc3** [comment] 2016-07-04 19:28
Have you tried without plugins?

**Comment by Techcable** [comment] 2016-07-04 19:44
Does it happen on Paper?

**Comment by Techcable** [comment] 2016-07-04 19:48
Duplicate of PaperMC/Paper#352

**Closed** 2016-07-04 19:49 UTC
Labels: duplicate
