### ISSUE TITLE
Crafting Lag related to TacoSpigot

### ISSUE THREAD

**Issue by PsychoLynx** [TacoSpigot/TacoSpigot#36] opened 2016-06-07 12:52 UTC
Hey! 

Running build 61 of Taco, it is almost impossible to craft anything as each time you try to take out what you've crafted, the ingredients reappear in your inventory (tested with a furnace). No plugins, no such lag apparent when using latest 1.9.4 Spigot or Paper, which leads me to think it's due to Taco.

**Comment by mcarey10** [comment] 2016-06-07 19:00
I tested it with paperspigot and crafting works fine, so I believe it's something to do with taco.

**Comment by Techcable** [comment] 2016-06-09 06:18
Duplicate of #35

**Closed by Techcable** 2016-06-09 06:18 UTC
